#- name: Get the my_sql_root _pass from aws secret manager
#  debug:
#    msg: "{{ lookup('amazon.aws.aws_secret', 'roboshop/my_sql_root_password' , region='us-east-1') }}"

- name: print password from vars -> main.yaml which was stored as root_password from aws secret manager
  debug:
    msg: "{{ root_password.MY_SQL_ROOT_PASSWORD }}"


- name: Change hostname for "{{ component }}"
  hostname:
    name: mysql.trivikram.online

- name: Install MySQL Server for "{{ component }}"
  dnf:
    name: mysql-server
    state: present

- name: Start and Enable MySQL Service "{{ component }}"
  service:
    name: mysqld
    state: started
    enabled: yes

- name: setup root password "{{ component }}"
  command: mysql_secure_installation --set-root-pass "{{ root_password.MY_SQL_ROOT_PASSWORD }}"
  #command: mysql_secure_installation --set-root-pass "{{ MY_SQL_ROOT_PASSWORD }}"